apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eqtytddtg-python 
  janus-idp.io/tekton: eqtytddtg-python
  backstage.io/kubernetes-id: eqtytddtg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eqtytddtg-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  